version: "3.8"

services:
  bot:
    build: .
    container_name: trading-bot
    env_file:
      - .env
    restart: unless-stopped
    command: ["python", "-u", "app/main.py"]
    ports:
      - "80:5000"